### ISSUE TITLE
runConsensus.py

### ISSUE THREAD

**Issue by tkosciolek** [psipred/fragfold_idp#10]
I think that `runConsensus.py` script is making a wrong assertion:
```
if not glob.glob(args.ffidp_path+args.input_name+"/Dynamine_b_*"):
    print("Dynamine results are not available")
    exit(1)
```
There is a flag `--dynamine_path` which should be used here, instead of `ffidp_path`... also there is `indir` flag which adds even more confusion.

Then, I got the PyBrain error, for which we already know the fix... but it gets even more wooly:
```
input file lengths do not match
Traceback (most recent call last):
  File "bin/runConsensus.py", line 411, in <module>
    out_fp=args.outdir+args.input_name+".consensus"
  File "bin/runConsensus.py", line 58, in run_network
    inp = network_input(ffidp_fp, dm_fp, ss_fp, aln_fp)
  File "bin/runConsensus.py", line 124, in network_input
    _feat = [dm[res], ff[res], ss[res][0], ss[res][1], ss[res][2]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by DanBuchan** [comment]
Yes that should be dynamine_path and we can lose the indir flag. I have fixed those in master.

I have zero idea what the bug in the run_network() call is. You'll probably have an easier time tracking that down as you wrote the numpy code and I have zero experience with numpy

**Comment by tkosciolek** [comment]
The subsequent `IndexError` is there because I was using the wrong `.ss` file. Once I give it the correct file, works fine!
But it might be worth a thought how not to confuse `.ss` and `.ss2` files from PSIPRED?
and! ...PSIPRED `ss2` file has a header (by default) which is not readable by `runConsensus.py`. I will add a small fix, to make it less error-prone.

**Comment by tkosciolek** [comment]
Since the issues have been resolved I declare this issue closed!

**Comment by DanBuchan** [comment]
Again this issue is handled by running the FFIDP.py script which will output the files you do need.
