### ISSUE TITLE
RSEVAL.py

### ISSUE THREAD

**Issue by tkosciolek** [psipred/fragfold_idp#11]
I ran the script from the main FFIDP directory: 
`python bin/RSEVAL.py -i tmp/2KJV.pdb_ens -j example_data/2KJV.cons`

For some reason, even if the paths are specified correctly, I get an error:
```
Traceback (most recent call last):
  File "bin/RSEVAL.py", line 75, in <module>
    profile1 = read_profile(args.results_dir+"/"+args.i1)
  File "bin/RSEVAL.py", line 20, in read_profile
    with open(fp, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkosciolek/test_ffidp/fragfold_idp/bin/../output//tmp/2KJV.pdb_ens'
```

seems like lines 75 and 76 (`profile1` and `profile2`) have `results_dir` argument, instead of reading `i1` and `i2` directly. Is there a reason for that?

When I change `RSEVAL.py` to:
```
profile1 = read_profile(args.i1)
profile2 = read_profile(args.i2)
```
the command on top works no problem.

**Comment by DanBuchan** [comment]
RSEVAL.py takes the names of the files to analyse not the paths, by default it assumes they are in the `output/` directory. If you want them to be elsewhere you need provide the `--results_dir` flag

for instance move 2KJV.pdb_ens to `example_data/` and then run

```
python bin/RSEVAL.py -i 2KJV.pdb_ens -j 2KJV.cons --results_dir example_data/
```

That should work.

I've change the description of the -i and -j options to reflect this.
