### ISSUE TITLE
Run notes T.Kosciolek 8th of Feb

### ISSUE THREAD

**Issue by DanBuchan** [psipred/fragfold_idp#7]
1. code line should read `python bin/runSeqAnalysis.py --input example_data/2KJV.pdb`, if we're assuming the user should run it from main FFIDP directory  
```
Got this error on psipred:
> /home/tkosciolek/test_ffidp/psipred/bin/psipass2: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/tkosciolek/test_ffidp/psipred/bin/psipass2)  
```
but obviously it's not your fault I've got GLIBC_2.12  
Otherwise works OK.

2. Some paths seem to be a little bit funky. This is an example from `nfpar` file generated by the script: `/home/tkosciolek/test_ffidp/fragfold_idp/bin/../output/a2117b92-ee8a-11e6-96ec-6805ca3313b9.ffaln`

3. RMSDclust gives me an error:
```
> Running RMSD Ensemble Clustering
PDB file error!
RMSD Ensemble Clustering Non Zero Exit status: 255  
```
 but the program works fine when I run it manually.  
JAVA (PFclust) also produces errors:

```> Exception in thread "main" java.lang.UnsupportedClassVersionError: main/Main : Unsupported major.minor version 52.0```

 Again, that's probably not something we can do anything about.

**Comment by DanBuchan** [comment]
2. Yes the paths are a little funky that is due to the way python detects where the scripts are and where the output directory is. Not a great deal I can do about that.

**Comment by DanBuchan** [comment]
First up paths.yml things, in addressing some other things you raised I've overhauled the path.yml file. It is more complex but it will fix some issues that might arise with the ansible install. On the flipside I've added some user helpful explanations.

Now on to the points your raised above:
1. good catch, changed the paths to include bin.
glibc problem for psipred is now fixed by having psipred recompile all it's binaries on install

2. paths are indeed funky inside the nfpar files, but we aren't expecting users to read/edit the nfpar files are we?
I note though this will make the nfpar files non-portable (i.e. if you run runSeqAnalysis.py on one machine and then want to move all the nfpar files on to your cloud machine). So I've added a ffaln_dir control to paths.yml so people can set this for the relevant location on their cloud service. I've also update the docs to make it clear what people need to do when running fragfold on a cluster.

3. Having fixed the above I'm now running components on Mac
`runSeqanalysis` appears fine
`runFragfold` appears fine
`runFFID.py`: I get a cannot execute binary `bin/rmsdclust_RMSDarray: cannot execute binary file`
this requires that users recompile the binaries in src/ I have added this step to the README and it runs correctly

`dynamine.py`:
In OSX even with a python2 virtualenv I experience some pathing problems when a script tries to finding biopython. My general experience is that system python on Mac is annoying and this is not the first project/download where my Mac fails to find the correctly installed module. This is unsolvable by us unless we require people completely uninstall all pythons on their mac and install a fresh one. I solved this by forcing the pip version when installing biopython, YMMV. 
`pip2 install biopython`
Having fixed this the dynamine server does not appear to be responding correctly. I have emailed them about it.

`runConsensus.py`:
This obviously fails in the absence of a dynamine results. Should we go ahead an build a consensus in the absence of the dynamine results? In the meantime I've added an if that halt execution if it can't find the dynamine results

**Comment by DanBuchan** [comment]
3. cont... for runFFID.py I get a can not execute binary
`bin/rmsdclust_RMSDarray: cannot execute binary file`
this requires that users recompile the binaries in src/
I have added this step to the README and it runs correctly

dynamine.py
In OSX even with a python2 virtualenv I experience some pathing problems when a script tries to finding biopython. My general experience is that system python on Mac is annoying and this is not the first project/download where my Mac fails to find the correctly installed module. This is unsolvable by us unless we require people completely uninstall all pythons on their mac and install a fresh one. I solved this by forcing the pip version when installing biopython, YMMV. 
`pip2 install biopython`
Having fixed this the dynamine server does not appear to be responding correctly. I have emailed them about it.

**Comment by DanBuchan** [comment]
3. cont... 
`runConsensus.py`:
This obviously fails in the absence of a dynamine results. Should we go ahead an build a consensus in the absence of the dynamine results? In the meantime I've added an if that halt execution if it can't find the dynamine results

**Comment by DanBuchan** [comment]
3. cont...

Ok dynamine is now working again, so on we go...

`dynamine`:
working while the server is live. Have added a point to the README that users can't continue if dynamine does not respond correctly

`runConsensus.py`:
failed to find the pybrain structure module even though pybrain installed without fault from the requirements.txt file. Have added a note to installation step 3 to indicate that users may have to manually install pybrain if runConsensus.py fails.

`slidingWindow.py`:
Ran without fault

`RSEVAL.py`:
Path typo for outputs, fixed.
.consensus file runConsensus produces has blanklines? This caused the read_profile() parser in RSEVAL.py to fail. I've added a line to skip over blanklines. Important need to double check that it is acceptable that runConsensus outputs a file with some blank lines.

**Comment by tkosciolek** [comment]
@DanBuchan this is great! Thanks for analysing this comprehensively.
I will go through all of the steps and comments (hopefully) tomorrow.

**Comment by tkosciolek** [comment]
`RSEVAL.py` shouldn't produce blank lines. Thanks for fixing this.

For scripts which do not produce a file output, but a `np.array` I would simply do:
`np.savetxt(fname, np_array, fmt='%.2f')`
From what you mentioned these scripts and functions are:
```
runConsensus.py (run_network() function)
runFFIDP.py (run_Sliding_Window() function)
```

Is there anything else to resolve?

**Comment by DanBuchan** [comment]
I think you're not understanding my point about dumping the np_array to file. 

Theses data appear to be predictions that the user should probably be able to open and understand. It is not good enough that the file is just a list of anonymous floats.

It should probably be a csv file that is something like
```
position,residue,score
1,A,1.03
2,G,2.40
3,C,.5.74
4,W,2.30
```

Now you can see that the numbers relate to residue positions and then in the docs we can explain what the values/scores are so the user can interpret them. 

Right now you run all these components and you get no file that a user can open and interpret to understand which residues are or are not disoredered. Which is kind of a problem for a disorder predictor.

Specifically we need human readable versions of the files ending `.ffidp`,`.consensus`,`.pdb_ens`. And we should have a note in the readme explain what the numbers in these files mean

**Comment by tkosciolek** [comment]
You're totally right! I was the only end-user of this for probably 3 years, so to me seeing a list of numbers was totally natural. I agree, that we should probably produce something like what you proposed, or what DynaMine produces, i.e.
```
A    1.03
G    2.40
C    5.74
W    2.30
```

**Comment by DanBuchan** [comment]
Can you add an additional CSV output wherever there is a np.savetxt() call (i.e. where we produce the files .ffidp,.consensus,.pdb_en)

**Comment by tkosciolek** [comment]
Will do, once I squash other bugs, so that I'm in sync with master... right now, I generated loads of surplus files locally.

**Comment by tkosciolek** [comment]
Updated writing pretty files in `runConsensus.py`, `runFFIDP.py` and `SlidingWindow.py`.
runConsensus and runFFIDP were tested and work as expected.
See PR #12

**Comment by DanBuchan** [comment]
closing this issue as there is now a pull request that completes this work
