### ISSUE TITLE
runFFIDP.py RMSDclust error

### ISSUE THREAD

**Issue by tkosciolek** [psipred/fragfold_idp#9]
After installing FFIDP anew (this time all seems to work!) I'm still having problems with `runFFIDP.py`
```
Running RMSD Ensemble Clustering
PDB file error!
RMSD Ensemble Clustering Non Zero Exit status: 255
```
When I run `rmsdclust_RMSDarray` (e.g. `bin/rmsdclust_RMSDarray 2KJV.ens 2KJV_`) manually it works fine.

**Comment by DanBuchan** [comment]
I can't replicate this error

In the runFFIDP.py I have uncommented the print at line 315 to check is happening when it tries to rmsdclust. For me it prints
```
/Users/dbuchan/Code/fragfold_idp/bin/rmsdclust_RMSDarray /Users/dbuchan/Code/fragfold_idp/bin/../output/e62fe446-f9c3-11e6-9363-989096c13ee6.ens /Users/dbuchan/Code/fragfold_idp/bin/../output/e62fe446-f9c3-11e6-9363-989096c13ee6_
```
This command appears to execute correctly

What command do you see?

I note that if you give runFFIDP.py the WRONG UUID you get the error you are seeing.

**Comment by tkosciolek** [comment]
My bad... I followed your instructions and noticed that the script tried to run `2KJV.ens.ens`, instead of `2KJV.ens`.
Otherwise works fine, but I noticed a small problem:
I run `runFFIDP.py` from the main fragfold_idp folder: `python bin/runFFIDP.py --input_name 2KJV --indir example_data/ --outdir tmp`, 
so `RMSDclust` writes the output to `./`, but `PFClust` expects it in `example_data/`.
When I run it from inside the folder it works fine.

**Comment by DanBuchan** [comment]
Yeah, if you change the outdir in one script you have to echo that change in the indir of the subsequent scripts.

We should probably make that obvious in README. The general idea is that you would run FFIDP.py (providing and alternate indir and outdir) and it would tell you all the commands you need and you'd just run them. Which would ameliorate this problem

**Comment by tkosciolek** [comment]
OK, in this case let's leave it as-is.
Issue closed!
